
name: Test Makefile

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Pull images, pack quickstart, test-submission
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        proc: ['cpu']
    env:
      SHA_TAG: ${{ matrix.proc }}-${{ github.sha }}
      LATEST_TAG: ${{ matrix.proc }}-latest
      GITHUB_ACTIONS_NO_TTY: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Test zipping submission_quickstart
        run: |
          make pack-quickstart

      - name: Pull latest image and run submission in container
        run: |
          make pull
          make test-submission
